
- name: "Update Node js repo"
  shell: wget -qO- https://deb.nodesource.com/setup_14.x | sudo -E bash -
  
- name: "Update/upgrade packages"
  become: yes
  apt:
    update_cache: true

- name: "Install nodejs & npm"
  become: yes
  apt:
    name: ["nodejs","npm"]
    state: present

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes